server:
  port: 8084

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: ${USER}
    password: 123123
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
