CREATE TABLE OAUTH_USER (
  ID         BIGSERIAL                   NOT NULL PRIMARY KEY,
  NAME       VARCHAR(255)                NOT NULL,
  USERNAME   VARCHAR(255)                NOT NULL UNIQUE,
  PASSWORD   VARCHAR(255)                NOT NULL,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);