CREATE TABLE OAUTH_AUTHORITY (
  ID         BIGSERIAL                   NOT NULL PRIMARY KEY,
  AUTHORITY  VARCHAR(100)                NOT NULL,
  USER_ID    BIGINT                      NOT NULL REFERENCES OAUTH_USER (id),
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);