INSERT INTO OAUTH_CLIENT_DETAILS (CLIENT_ID,
                                  CLIENT_SECRET,
                                  RESOURCE_IDS,
                                  SCOPE,
                                  AUTHORIZED_GRANT_TYPES,
                                  WEB_SERVER_REDIRECT_URI,
                                  AUTHORITIES,
                                  ACCESS_TOKEN_VALIDITY,
                                  REFRESH_TOKEN_VALIDITY,
                                  ADDITIONAL_INFORMATION,
                                  AUTOAPPROVE)
VALUES ('api-gateway',
        '$2a$10$2pZvMJuhPdi8ZWkX69NoPudL78ssNHmA/61hGK4tN0C91GOETKy/y',
        'apigateway',
        'read,write',
        'password,refresh_token',
        null,
        'USER',
        3600,
        7200,
        null,
        1);